name: PR Checklist for Frontend

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, review_requested, synchronize, labeled]
  workflow_call:

jobs:
  check:
    name: Add Checklist if "frontend" Label is Present
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels and add checklist
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              console.log("No PR context found.");
              return;
            }

            const labels = pr.labels.map(label => label.name);
            if (!labels.includes("frontend")) {
              console.log("Skipping checklist: PR does not have 'frontend' label.");
              return;
            }

            const checklist = `
            ## ✅ PR Checklist for Frontend  
            - [ ] Código revisado  
            - [ ] Pruebas unitarias agregadas  
            - [ ] Documentación actualizada  
            - [ ] Aprobación de al menos un revisor  
            `;

            github.rest.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: checklist
            });

