name: Java CI - Tests

on:
  push:
    branches: [ backend/tarea_17/test_workflow ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Cache Maven local repo
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

 
    - name: Generate .env file for tests
      run: |
        cat > .env <<'EOF'
        # ---------- variables usadas en perfil "test" ----------
        CAMYO_APP_JWT_SECRET=dummy_token_for_ci

        # BBDD H2 en memoria
        SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
        SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
        SPRING_DATASOURCE_USERNAME=sa
        SPRING_DATASOURCE_PASSWORD=
        SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect

        # Clave Stripe sintácticamente válida (pero inerte)
        STRIPE_API_KEY=sk_test_1234567890abcdefghijklmnopqrstuv
        EOF

        # Copiar al módulo backend (Dotenv lo busca ahí)
        cp .env backend/.env

        echo "::group::.env content"
        cat .env
        echo "::endgroup::"

    - name: Run Maven unit tests
      working-directory: backend
      run: |
        mvn -B clean test \
          -Dspring.profiles.active=test \
          -Dsurefire.excludedTests='**/PagoControllerTests.java,**/AuthServiceTest.java,**/CamioneroServiceTests.java,**/EmpresaServiceTests.java,**/BackendApplicationTests.java'
