name: Java CI - Test Automático

on: [push, pull_request]

jobs:
   test:
     name: Ejecutar tests con Maven
     runs-on: ubuntu-latest
 

     env:
      DB_DATABASE: camyo_db_test
      DB_USER: root
      DB_PASSWORD: root
  
     steps:
       - name: Set up MySQL
         run: |
           sudo systemctl start mysql.service
           mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

       - name: Checkout del código
         uses: actions/checkout@v3
 
       - name: Configurar JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
 
       - name: Cache de dependencias Maven
         uses: actions/cache@v3
         with:
           path: ~/.m2
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven

       - name: Copiar .env
         run: cp ./backend/.env.example ./backend/.env

       - name: Copiar application.properties
         run: |
           cp application-test.properties.example application-test.properties
           sed -i 's/YOUR_PASSWORD_HERE/root/g' application-test.properties
           sed -i 's/create-drop/create/g' application-test.properties
         working-directory: ./backend/src/test/resources
          
      
       - name: Ejecutar tests
         run:  mvn "-Dtest=!PagoControllerTests,!CamioneroServiceTests,!AuthServiceTest" test         ## Excluded tests that need external keys, they are not included for security reasons
         working-directory: ./backend
